<a href="https://colab.research.google.com/github/RahulYadav71/Data-Science-and-Ai-python-Programming-Module--01/blob/Python-Programing-Module-1/DS%26Ai_Module_1_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello Data Science")

Hello Data Science


# **Variables**

In [ ]:
name = "Rahul"
age = 21
salary = 50000
print(name)
print(age)
print(salary)

Rahul
21
50000


# **Assigning Values to Variables**

1. Basic Assigning


In [ ]:
x = 5
y = 3.14
z = 'Hi'
print(x)
print(y)
print(z)

5
3.14
Hi


2. Dynamic


In [ ]:
x = 10
x = 'Rahul'
print(x)
print(type(x))

Rahul
<class 'str'>


3. Assigning Same Values

In [ ]:
a = b = c = 100
print(a, b, c)

100 100 100


4. Assigning Different Values

In [ ]:
x, y, z = 1, 2.5 , "Python"
print(x, y, z)

1 2.5 Python


# **DATA TYPES**

**Numeric Data Types**
1. Integer

In [ ]:
age = 23
print(type(age))

<class 'int'>


2. Float

In [ ]:
price = 99.45
print(type(price))

<class 'float'>


3. Complex

In [ ]:
x = 3 + 4j
print(x)
print(type(x))

(3+4j)
<class 'complex'>


# **Sequence Data Types**

1. String


In [ ]:
s = 'WELCOME TO BBD'
print(s)
print(type(s))

WELCOME TO BBD
<class 'str'>


2. List

In [ ]:
a =[1,2,3]
print(a)
print(type(a))
b = ["BBD", "BBD", "BBD", 4,5]
print(b)
print(type(b))

[1, 2, 3]
<class 'list'>
['BBD', 'BBD', 'BBD', 4, 5]
<class 'list'>


3. Tuples

In [ ]:
t1= (1,)
print(type(t1))

t2= ('BBD', 'BBD', 'BBD', 1, 2)
print(t2)
print(t2)

<class 'tuple'>
('BBD', 'BBD', 'BBD', 1, 2)
('BBD', 'BBD', 'BBD', 1, 2)


# **Set Data Type**

Set

In [ ]:
s1 = {"a","a","b","c","b"}
print(s1)

s2 = {"BBD", "FOR", "BBD"}
for i in s2:
  print(i)

{'a', 'b', 'c'}
FOR
BBD


# **Dictionary Data Types**

In [ ]:
d = {1:'BBD', 2:'for', 3:'BBD'}
print(d[1])
print(d.get(2))


BBD
for


# **OPERATORS**

1. Arithmetic Operators

In [ ]:
a = 15
b = 4
print("Addition:", a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("Modulus:",a%b)
print("Floor Division:",a//b)
print("Exponentiation:",a ** b)

Addition: 19
Subtraction: 11
Multiplication: 60
Division: 3.75
Modulus: 3
Floor Division: 3
Exponentiation: 50625


2. Comparison Operators

In [ ]:
a=13
b=33
print(a==b)
print(a!=b)
print(a>b)
print(a<b)
print(a>=b)
print(a<=b)

False
True
False
True
False
True


3. Logical Operators

In [ ]:
a= True
b = False
print(a and b)
print(a or b)
print(not a)

False
True
False


4. Bitwise Operators


In [ ]:
a = 10
b = 4
print(~a)
print(a<<b)
print(a&b)
print(a^b)
print(a | b)
print(a>>b)

-11
160
0
14
14
0


5. Assignment Operators

In [ ]:
a = 10
b = a
print(b)
b += a
print(b)
b -= a
print(b)
b *= a
print(b)
b <<= a
print(b)

10
20
10
100
102400


6. Identity Operators

In [ ]:
a = 10
b = 20
c = a

print(a is not b)
print(a is c)

True
True


7. Membership Operators


In [ ]:
x = 24
y = 20
my_list = [10,20,30,40,50]
if (x not in my_list):
  print("x is NOT present in the given list")
else:
  print("x is present in the given list")

if (y in my_list):
    print("y is present in the given list")
else:
    print("y is NOT present in the given list")

x is NOT present in the given list
y is present in the given list


8. Ternary Operator

In [ ]:
a , b = 15, 20
min = a if a < b else b
print (min)

15


# **IMPORTANT QUESTIONS**
 QUESTION-1. Take two numbers as input from the user and perform all arithmetic Operations

In [ ]:
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
print("Addition:", a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("Modulus:",a%b)
print("Floor Division:",a//b)
print("Exponentiation:",a ** b)

Enter first number: 1
Enter second number: 2
Addition: 3
Subtraction: -1
Multiplication: 2
Division: 0.5
Modulus: 1
Floor Division: 0
Exponentiation: 1


QUESTION-2. Check whether a specific course is available in the course catalog


In [ ]:
courses = ["Python", "Java", "Data Science", "AI", "Machine Learning"]

course_name = input("Enter course name: ")

if course_name in courses:
    print("Course is available in the catalog.")
else:
    print("Course is not available in the catalog.")


QUESTION-3. Create a simple login validation system using a username and password

In [ ]:
username = 'admin'
password = '1234'

user_name = input("enter username:")
user_pass = input("enter passsword:")

if user_name == username and user_pass == password:
  print("Login Successful")
else:
  print("Login Failed")

**QUESTION-4.** An employee is eligible for a bonus only if:

                .Salary is greater than 30,000
                .Experience is greater than 2 years
                Write a program to determine eligibility.

# **CONDITIONAL STATEMENTS**
1. **If Statement**

In [ ]:
age = 19
if age >= 18:
  print("You are eligible to vote")

# **Short Hand if**
if statements in a single line. it is useful when only one statement needs to be executed.

In [ ]:
age = 19
if age > 18: print("Eligible to vote")

2. **If else Statement**

if else statement is used to execute one block of code when the condition is True and another block when the condition is false.

In [ ]:
age = 10
if age <= 12:
   print("Travel for free.")
else:
  print("Pay for Ticket.")

**3. If-elif-else Statement**

elif statement is used to check multiple conditions in a program . it executes a block. of code when its conditions evaluates to true after previous conditions evaluate to false.




In [ ]:
age = 25;
if age <= 12:
  print("child.")
elif age <= 19:
  print("Teenager.")
elif age <= 35:
  print("Young Adult.")
else:
  print("Adult.")

**4. Nested if-else Statements**

In [ ]:
age = 70
is_member = True
if age >= 60:
  if is_member:
   print("30% senior discount!")
  else:
   print("20% senior discount!")
else:
  print("Not eligible for a senior discount!")

# **LOOPS**
**1. for Loop**

In [ ]:
for i in range (1,6):
  print(i)

**Example 2: Iterate through a list**

In [ ]:
fruits = ["Apple" , "Banana" , "Mango"]

for fruit in fruits:
  print(fruit)

**2. while Loop**

In [ ]:
count = 1
while count <= 5:
  print(count)
  count += 1

**3. Loop Control Statements**

**A. Break**

In [ ]:
for i in range (1,10):
  if i == 5:
    break
  print(i)

**B. Continue**

In [ ]:
for i in range (1, 6):
  if i == 3:
    continue
print(i)

**C. Pass**

Placeholder statement

In [ ]:
for i in range (5):
  pass
  print ("loop completed:")

**4. Nested loops**

A loop inside another loop.

In [ ]:
for i in range(1, 4):
  for j in range(1, 4):
    print(i, j)

# **IMPORTANT QUESTIONS**

QUESTION 1:- Take a number from the user and calculate the sum of all numbers 1 to N.

In [ ]:
n = int(input("Enter a number: "))

sum = 0

for i in range(1, n + 1):
    sum += i

print("Sum =", sum)

QUESTION 2:- Allow the user to enter a password until the correct password is entered.

In [ ]:
correct_password = "mysecretpassword"
entered_password = ""

while entered_password != correct_password:
    entered_password = input("Enter the password: ")
    if entered_password != correct_password:
        print("Incorrect password. Please try again.")

print("Correct password! Login successful.")

QUESTION 3:- Find how many positive numbers are present in a list.


In [ ]:
numbers = [10, -5, 20, 0, -8, 15, 7]

count = 0

for num in numbers:
    if num > 0:
        count += 1

print("Number of positive numbers:", count)

QUESTION 4:-Check Whether Monthly Sales Achieved the Target.


In [ ]:
sales = float(input("Enter monthly sales: "))
target = float(input("Enter sales target: "))

if sales >= target:
    print("Target Achieved!")
else:
    print("Target Not Achieved!")

QUESTION 5:-Print all even numbers between 1 and 50 using a loop.


In [ ]:
for i in range(1, 51):
    if i % 2 == 0:
        print(i)

# **FUNCTIONS**

# **1. FUNCTIONS in PYTHON**

Block of statements that perform a specific task.

 .def func_name(param1, param2): #some works

 .return val

** Built in fuctions**

print()

len()

type()

range()

Functions in python

In [ ]:
def greet():
  print("Welcome to BBD")
greet()

# 2. **FUNCTIONS with PARAMETERS**

*Parameters allow us to pass values into a function.*

In [ ]:
def greet(name):
  print("Hello", name)

greet("Rahul")


# **3. FUNCTIONS with MULTIPLE PARAMETERS**

In [ ]:
def add(a, b):
    print(a+b)
add(10, 20)

# **4. FUNCTIONS with RETURN STATEMENT**

*Return sends a value back to the caller.*

In [ ]:
def square(num):
  return num * num
result = square(5)
print(result)


# **5. DEFAULT PARAMETERS**

In [ ]:
def country(name="India"):
  print("Country:", name)
country()
country("USA")

# **6. KEYWORD ARGUMENTS**

In [ ]:
def student(name, age):
  print(name, age)
student(age=22, name="Rahul")

# 7. VARIABLE LENGTH ARGUMENTS (*args)

Used when the number of arguments is unknown.

In [ ]:
def total(*numbers):
  print(sum(numbers))
total(10,20,30)

# **8. KEYWORD VARIABLE ARGUMENTS**

In [ ]:
def info(**details):
  print(details)
info(Name="Rahul", City="Lucknow")

# **8. LAMBDA FUNCTIONS**

small anonymous function.

In [ ]:
square= lambda x: x*x
print(square(5))

# **10. FUNCTIONS with LIST**

In [ ]:
def average(numbers):
  return sum(numbers)/len(numbers)
data = [10,20,30,40,50]
print(average(data))

# **11. FUNCTIONS with NumPy ARRAYS**

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr)

# **QUESTIONS**

# **QUESTION 1:-Employee Salary Calculator**

 Create a function that calculates the final salary of an employee after adding bonus and deducting tax.

In [ ]:
def calculate_final_salary(base_salary, bonus_percentage, tax_percentage):
  """Calculates the final salary after adding bonus and deducting tax."""
  bonus_amount = base_salary * (bonus_percentage / 100)
  salary_after_bonus = base_salary + bonus_amount
  tax_amount = salary_after_bonus * (tax_percentage / 100)
  final_salary = salary_after_bonus - tax_amount
  return final_salary

# Example usage:
base = float(input("Enter base salary: "))
bonus_rate = float(input("Enter bonus percentage: "))
tax_rate = float(input("Enter tax percentage: "))

final_sal = calculate_final_salary(base, bonus_rate, tax_rate)
print(f"The final salary is: {final_sal:.2f}")

# **QUESTION 2:- Student Result Analysis System**

Create a function that accepts marks of multiple subjects using *args and calculates total, average and grade.

In [ ]:
def calculate_result(*marks):
    total = sum(marks)
    average = total / len(marks)

    if average >= 90:
        grade = "A+"
    elif average >= 80:
        grade = "A"
    elif average >= 70:
        grade = "B"
    elif average >= 60:
        grade = "C"
    elif average >= 50:
        grade = "D"
    else:
        grade = "F"

    print("Total Marks:", total)
    print("Average Marks:", average)
    print("Grade:", grade)

# Example function call
calculate_result(85, 90, 78, 88, 92)

# **QUESTION 3:- Customer Information Management System**

Use **kwargs to store customer details dynamically.

In [ ]:
def customer_details(**kwargs):
    print("Customer Details:")
    for key, value in kwargs.items():
        print(f"{key}: {value}")

# Function call
customer_details(
    Name="Rahul Yadav",
    Age=21,
    City="Lucknow",
    Phone="9693519956",
    Email="ry808442@gmail.com"
)

# **File Handling in Python**

# **1. Opening a file**

In [ ]:
file = open("/content/data.txt", "r", encoding='latin-1')
print(file.read())
file.close()

# **2. Reading a file**

read()

Read entire file.

In [ ]:
file = open("/content/data.txt", "r")
content = file.read()
print(content)
file.close()

readline()

Reads one line at a time.

In [ ]:
file = open("/content/data.txt", "r")
print(file.readline())
print(file.readline())

file.close()

# **3. Writing into a File**

w Mode

Creates a new file or overwrites existing content.

In [ ]:
file = open("/content/data.txt", "w")
file.write("Name : Rahul Yadav\n")
file.write("Course : Python\n")
file.write("Batch : VIII\n")
file.close()
print("Data Written Successfully")

# **4. Appending Data**

a Mode

Adds data at the end.

In [ ]:
file = open("data.txt", "a")
file.write("Welcome to BBD University\n")
file.close()
print("Data Added Successfully")

# Exception Handling

In [ ]:
try:
  #code that may cause an error..
  result = 10/0
except ZeroDivisionError:
  print("Cannot divide by zero")
finally:
  print("Execution Completed")

# **Common Exception in Data Science**

1. FileNotFoundError

  When loading datasets:

In [ ]:
import pandas as pd

try:
  df = pd.read_csv("sales.csv")
except FileNotFoundError:
  print("Dataset file not found")

2. ValueError

When converting data types:

In [ ]:
try:
  age = int("twenty")
except ValueError:
  print("Invalid value for age")

3. KeyError

When accessing a non-existent column in a DataFrame.

In [ ]:
import pandas as pd

df = pd.DataFrame({"Name": ["John"]})

try:
  print(df["Age"])
except KeyError:
  print("Column does not exist")


4. IndexError

When accessing an invalid row index:

In [ ]:
data = [10, 20, 30]

try:
  print(data[5])
except IndexError:
  print("Index out of range")

5. TypeError

In [ ]:
try:
  result = "10" + 5
except TypeError:
  print("Incompatible data types")

# Handling Multiple Exceptions

In [ ]:

try:
    value = int(input("Enter the number: "))
    result = 100 / value
    print("Result:", result)

except ValueError:
    print("Please enter a valid integer.")

except ZeroDivisionError:
    print("Division by zero is not allowed.")


# **Object-Oriented Programming(OOP)**


# **(i) What is an Object?**




An object is an instance of a class.

In [ ]:
class Student:
  pass
s1 = Student()
s2 = Student()
print(type(s1))


# **(ii) Constructor (init Method)**

A constructor automatically runs when an object is created.

In [ ]:
class Student:
  def __init__(self, name, age):
    self.name = name
    self.age = age
s1 = Student("Rahul", 21)
print(s1.name)
print(s1.age)

# **(iii) Instance Variables**

In [ ]:
class Student:
  def __init__(self, name, marks):
    self.name = name
    self.marks = marks

  def display(self):
    print(f"Name: {self.name}")
    print(f"Marks: {self.marks}")

s1 = Student("Rahul", 90)
s1.display()

# **(iv) Methods**

Functions inside a class.

In [ ]:
class Student:
  def __init__(self, name):
    self.name = name


  def display(self):
    print(f"Name: {self.name}")
s1 = Student("Rahul")
s1.display()

# **Four Pillars of OOP**



# 1. Encapsulation

It is the technique of hiding an objects internal data and allowing controlled access through methods.

In [ ]:
class BankAccount:
    def __init__(self, balance):
        self.__balance = balance

    def deposit(self, amount):
        if amount > 0:
            self.__balance += amount
            print(f"${amount} Deposited Successfully")
        else:
            print("Invalid deposit amount")

    def withdraw(self, amount):
        if amount <= self.__balance:
            self.__balance -= amount
            print(f"${amount} Withdrawn Successfully")
        else:
            print("Insufficient balance")

    def show_balance(self):
        print("Current Balance:", self.__balance)

obj = BankAccount(1000)
obj.deposit(500)
obj.withdraw(200)
obj.show_balance()

# **2. Inheritance**

It is an OOP concept in which a child class acquires the properties (attributes) and behaviors (methods) of an existing parent class.

In [ ]:
#Parent class
class Animal:

   def sound(self):
    print("Animals make different sounds.")

#Child class
class Dog(Animal):

   def bark(self):
    print("Dogs says: Bark Bark!")
#Object creation
dog = Dog()

dog.sound() #inherited method
dog.bark()  #Child class method

# **3. Polymorphism**

In [ ]:
class Animal:
  def sound(self):
    print("Animals makes a sounds.")

class Dog(Animal):
  def sound(self):
    print("Dogs Barks")

class Cat(Animal):
  def sound(self):
    print("Cat meows")

#Create objects
dog = Dog()
cat = Cat()

#Call the methods
dog.sound()
cat.sound()

# **4. Abstraction**

In [ ]:
from abc import ABC, abstractmethod

class Vehicle(ABC):
  def start(self):
    pass

class Car(Vehicle):
  def start(self):
    print("Car starts with a key")

class Bike(Vehicle):
  def start(self):
    print("Bike Start with a self Button")

#Create objects
car = Car()
bike = Bike()

car.start()
bike.start()

# **NumPy Fundamentals**

# What is NumPy?

NumPy(Numberic Python) is a powerful python library used for:

1. Numberic computations.

2. Working with arrays and matrices

3. Mathematical Operations

4. Data science and Machine learning

# Why Use NumPy?

1. faster than Python lists

2. less memory usage

3. supports multi-dimension arrays.

4. provide mathematical and statistical functions.

1. Installing NumPy

In [ ]:
pip install numpy

import NumPy

In [ ]:
import numpy as np

2. Creating NumPy arrays

# **ARRAYS**

An array is a data structure used to store multiple values of the same data type in a single variables.

In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

print(arr)
print(type(arr))

# **Two-Dimensional Array(2D)**

A***n 2D array is an array that stores data in rows and columns,just like an Excel sheet or a matrix.***

In [ ]:
import numpy as np
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr)

# **Three Dimensional Array(3D)**

***An 3D array is an array that has three dimensions:***

1. Depth(Layers)

2. Rows

3. Columns

In [ ]:
import numpy as np
arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(arr)

# **Array Attributes**

NumPy array attributes provide important information about an array, such as its dimensions, size , shape and data type.

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3],[4, 5, 6]])

print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)
print("Data Type:", arr.dtype)

# **Special Arrays**

# zeros Array np.zeros()

Creates an aarray where every element is 0.

In [ ]:
import numpy as np
arr = np.zeros((3, 3))
print(arr)

# ones Array np.ones()

Creates an array filled with 1.

In [ ]:
import numpy as np

arr = np.ones((3, 4))

print(arr)

# **np.empty()**

Creates an array without initializing values.

In [ ]:
import numpy as np

arr = np.empty((2, 3))

print(arr)

# **np.full()**

Creates an array filled with a specified value.

In [ ]:
import numpy as np

arr = np.full((2, 3), 7)

print(arr)

# **np.eye() -- Identity Matrix**

Creates an identity matrix.

In [ ]:
import numpy as np

arr = np.eye(3)

print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# np.arange()

Creates equally spaced values.

In [ ]:
import numpy as np

arr = np.arange(1,11)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


# np.linespace()

Creates equally spaced numbers between two values.

In [ ]:
import numpy as np

arr = np.linspace(1, 10, 5)

print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


## np.random.rand()

Random decimal numbers between 0 and 1.

In [ ]:
import numpy as np

arr = np.random.rand(3, 3)

print(arr)

[[0.8410539  0.03519403 0.16145173]
 [0.35298614 0.79317228 0.33416006]
 [0.2996427  0.84419617 0.31693421]]


# np.random.randint()

Random Integers.

In [ ]:
import numpy as np

arr = np.random.randint(1, 100, (3, 4))

print(arr)

[[ 8 45 46 66]
 [63 20 23 78]
 [86 25  4 69]]


# np.diag()

Creates a diagonal matrix or extracts diagonal elements.

In [ ]:
import numpy as np

arr = np.diag([1, 2, 3])

print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


# **PRACTICE QUESTIONS**

Ques.1:- Create a 3*4 NumPy array filled with zeros.

In [ ]:
import numpy as np

arr = np.zeros((3, 4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Ques.2:- Create a 4*5 NumPy array filled with ones.

In [ ]:
import numpy as np

arr = np.ones((4, 5))

print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Ques.3:-Create a 3*3 array using np.empty() and observe the values.
       Explain why the values are not initialized.

In [ ]:
import numpy as np

arr = np.empty((3, 3))

print(arr)

[[4.9e-324 0.0e+000 0.0e+000]
 [0.0e+000 9.9e-324 0.0e+000]
 [0.0e+000 0.0e+000 1.5e-323]]


Ques.4:-Create a 5*5 identity Matrix using NumPy.

In [ ]:
import numpy as np

arr = np.eye(5)

print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Ques.5:-Create a 4*4 diagonal matrix with diagonal elements 10,20.30, and 40.

In [ ]:
import numpy as np

arr = np.diag([10, 20, 30, 40])

print(arr)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


Ques.6:-Create a 5*5  array where every element is 99.

In [ ]:
import numpy as np

arr = np.full((5, 5), 99)

print(arr)

[[99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]]


Ques.7:-Generate 20 equally spaced numbers between 1 and 100.

In [ ]:
import numpy as np

arr = np.linspace(1, 100, 20)

print(arr)

[  1.           6.21052632  11.42105263  16.63157895  21.84210526
  27.05263158  32.26315789  37.47368421  42.68421053  47.89473684
  53.10526316  58.31578947  63.52631579  68.73684211  73.94736842
  79.15789474  84.36842105  89.57894737  94.78947368 100.        ]


Ques.8:-Create an array containing numbers from 10 to 100 with a step size of 10.

In [ ]:
import numpy as np

arr = np.arange(10, 101, 10)

print(arr)

[ 10  20  30  40  50  60  70  80  90 100]


Ques.9:-Generate a 4*4 matrix containing random integers between 1 and 100.

In [ ]:
import numpy as np

arr = np.random.randint(1, 101, (4, 4))

print(arr)

[[52 18 53 15]
 [39 41 18 78]
 [26 56 83 79]
 [80 57 89 15]]


Ques.10:- Write a program to create and display the following special arrays:

i) 3*3 Zero Array

In [ ]:
import numpy as np

arr = np.zeros((3, 3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


ii) 3*3 Ones Array

In [ ]:
import numpy as np

arr = np.ones((3, 3))

print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


iii) 3*3 Identity Matrix

In [ ]:
import numpy as np

arr = np.eye(3)

print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


iv) 3*3 Array filled with 7.

In [ ]:
import numpy as np

arr = np.full((3, 3), 7)

print(arr)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


v) 3*3  Random integer matrix (1-20)

In [ ]:
import numpy as np

arr = np.random.randint(1, 21, (3, 3))

print(arr)

[[17  8 15]
 [ 6 14  6]
 [ 8 15 13]]


# **Array Attributes**



Array attributes are the properties of a NumPy array that provide information about its structure,size,data type, memory usage, and dimensions.

# ***(i) ndim (Number of dimensions)***

   ndim tells us how many dimensions (axes) an array has:

In [ ]:
import numpy as np

arr = np.array([10, 20, 30])

print(arr.ndim)

1


In [ ]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr.ndim)


2


In [ ]:
arr = np.array([
    [
        [1, 2],
        [3, 4]
    ]
])
print(arr.ndim)

3


# ***(ii) Shape***

Shape tells us how many rows and columns are present.

In [ ]:
import numpy as np

arr = np.array([
    [10, 20,30],
    [40, 50, 60]
])

print(arr.shape)

(2, 3)


In [ ]:
arr = np.array([
    [
     [1, 2],
     [3, 4]
],
[

     [5, 6],
     [7, 8]
]


])
print(arr.shape)

(2, 2, 2)


# ***(iii) Size***

size means total no. of elements formula = Rows * columns

In [ ]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr.size)

6


# ***(iv) dtype***

dtype means data type of every element.

In [ ]:
import numpy as np

arr = np.array([10, 20, 30])

print(arr.dtype)

int64


In [ ]:
import numpy as np

arr = np.array([10.5, 20.5, 30.5])

print(arr.dtype)

float64


In [ ]:
import numpy as np

arr = np.array(["A", "B", "C"])

print(arr.dtype)

<U1


In [ ]:
arr = np.array([True, False, True])

print(arr.dtype)

bool


# ***(v) Itemsize***

itemsize tells memory occupied by one element. #Byte form

In [ ]:
arr = np.array([10, 20, 30])

print(arr.itemsize)

8


In [ ]:
arr = np.array([10.5, 20.5, 30.5])

print(arr.itemsize)

8


# ***(vi) Transpose***

Transpose means Rows becomes columns and columns become rows.

In [ ]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr.T)

[[10 40]
 [20 50]
 [30 60]]


# ***(vii) nbytes***

nbytes tells total memory occupied by the array formula = itemsize * size.

In [ ]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(arr.nbytes)

48


# **Practice Questions**

Ques.1:-Create a 1D NumPy array containing [10, 20, 30, 40, 50] and print its ndim.

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr.ndim)

1


Ques.2:- Create a 2D NumPy array with 4 rows and 3 columns. Print its shape.

In [ ]:
import numpy as np

arr = np.array([

                  [1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [10, 11, 12]
])

print(arr.shape)

(4, 3)


Ques.3:-Create 3D NumPy array of shape (2,3,4) and print its ndim and shape.

In [ ]:
import numpy as np

# Create a 3D array of shape (2, 3, 4) filled with sequential numbers
array_3d = np.arange(24).reshape(2, 3, 4)

# Print the array, its ndim, and its shape
print("--- 3D Array ---")
print(array_3d)
print("\n--- Properties ---")
print(f"Number of dimensions (ndim): {array_3d.ndim}")
print(f"Shape of the array: {array_3d.shape}")

--- 3D Array ---
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

--- Properties ---
Number of dimensions (ndim): 3
Shape of the array: (2, 3, 4)


Ques.4:-Create a 5*6 NumPy array using any values and print the total number of elements using size.

In [ ]:
import numpy as np

arr = np.array([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11, 12],

])
print(arr.size)



12


# What is Indexing?

Indexing means accessing a single element from an array using its position (index).

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])
print(arr[2])
print(arr[4])

10
30
50


# Negative Indexing

Negative indexing starts from the last element.

In [ ]:
import numpy as np

arr = np.array([10,20,30,40,50])

print(arr[-1])
print(arr[-2])
print(arr[-5])

50
40
10



# Indexing in 2D Arrays **bold text**

In [ ]:
import numpy as np

arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr[0,0])
print(arr[1,2])
print(arr[2,1])


10
60
80


# **Indexing in 3D Arrays**

In [ ]:
import numpy as np

arr = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
    ])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# **What is Slicing?**

Slicing means extracting multiple elements from an array.

array[start:stop:step] start--->Include

stop --> Excluded

step --> Increment

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70])

print(arr[1:5])
print(arr[:4])
print(arr[3:])
print(arr[:])


[20 30 40 50]
[10 20 30 40]
[40 50 60 70]
[10 20 30 40 50 60 70]


# Step Slicing

Skip one element every time.

In [ ]:
import numpy as np

arr= np.array([10, 20, 30, 40, 50, 60, 70])

print(arr[::2])
print(arr[1::2])
print(arr[::3])

[10 30 50 70]
[20 40 60]
[10 40 70]


# **Reverse Slicing**

Reverse Entire Array.

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70])

print(arr[::-1])

[70 60 50 40 30 20 10]


Reverse Alternate Elements.

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[::-2])

[50 30 10]


# **2D Slicing**

In [ ]:
import numpy as np

arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

print(arr[0,:]) #first row
print(arr[1,:]) #second row
print(arr[2,:]) #third row
print(arr[:,0]) #first column
print(arr[:,1]) #Second column
print(arr[:,2]) #third column

[10 20 30]
[40 50 60]
[70 80 90]
[10 40 70]
[20 50 80]
[30 60 90]


# **3D Slicing**

In [ ]:
import numpy as np

arr = np.array([
    [
    [1,2],
    [3,4]
    ],
    [
    [5,6],
    [7,8]
    ]
    ])
print(arr[0]) #first block
print(arr[1]) #
print(arr[1,0])
print(arr[:,:,1])


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[5 6]
[[2 4]
 [6 8]]


# **Practice Questions**

Create a 1D NumPy array containing numbers from 10 to 100 with a step of 10. Print the first,last and third elements using indexing.

In [ ]:
import numpy as np

# Create a 1D NumPy array from 10 to 100 with a step of 10
arr = np.arange(10, 101, 10)

print("Array:", arr)
print("First element:", arr[0])
print("Last element:", arr[-1])
print("Third element:", arr[2])

Array: [ 10  20  30  40  50  60  70  80  90 100]
First element: 10
Last element: 100
Third element: 30


Create a 1D NumPy array containing numbers from 1 to 20. Print elements from index 5 to index 12 using Slicing.

In [ ]:
import numpy as np

arr =

# Array Reshaping

*Reshaping means changing the structure (shape) of an array without changing its elements.*

# (i) reshape()


reshape() changes the dimensions of an array without changing its elements.

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

new_arr = arr.reshape(2, 3)

print(new_arr)

#shape (2,3)
#total elements 2*3=6



[[10 20 30]
 [40 50 60]]


In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])

new_array = arr.reshape(2,2,2)

print(new_array)

#shape(2,2,2)
#meaning 2 blocks and each block have 2 rows and 2 columns.

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# (ii) flatten

Converts a multi-dimensional array into a 1D array.

In [ ]:
import numpy as np

arr = np.array([
    [10, 20],
    [30, 40]
])

print(arr.flatten())

[10 20 30 40]


# (iii) Resize()

Changes the shape permanently.

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

arr.resize(2,3)

print(arr)

[[10 20 30]
 [40 50 60]]


# (v) swapaxes()

Used mostly for 3D and higher-dimensional arrays.

It swaps two axes.

In [ ]:
import numpy as np

arr = np.array([
    [
    [1, 2],
    [3, 4]
    ],
    [
    [5,6],
    [7,8]
    ]
])

print(arr.swapaxes(0,1))

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
